# -*- coding: utf-8 -*-
"""MST_1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/162rDu1psZURcEYp_5AWgb0EHVxM1lNV-
"""

!pip install nltk
import nltk
nltk.download('punkt')

story = """Once upon a time, in a kingdom far away, there lived a kind-hearted girl named Cinderella. She resided in a grand estate with her father, a loving man who cherished her dearly. Sadly, her mother passed away when Cinderella was just a child, leaving her alone with her father.

Years passed, and Cinderella's father eventually remarried, bringing home a new wife and her two daughters. Little did Cinderella know, this new family would bring with them hardship and sorrow.

Cinderella's stepmother was cold and cruel, showing favoritism only to her own daughters, Anastasia and Drizella. They were selfish and vain, taking pleasure in belittling Cinderella and making her life miserable.

Despite the mistreatment, Cinderella remained kind and gentle, finding solace in the company of the animals that roamed the estate. She spent her days caring for them and tending to her chores, hoping for a brighter future.

One day, word arrived that the prince was hosting a grand ball at the palace, inviting all eligible maidens to attend in hopes of finding his bride. Cinderella's stepfamily was ecstatic at the prospect of attending such a prestigious event, leaving her behind to tend to their needs.

As Cinderella watched her stepmother and stepsisters prepare for the ball, she couldn't help but dream of attending herself. However, her hopes were dashed when her stepmother forbade her from going, claiming she had no suitable attire.

Heartbroken but undeterred, Cinderella retreated to the attic, where she wept in solitude. Little did she know, her tears would summon a magical visitor who would change her fate forever.

In a flurry of light and sparkles, Cinderella's fairy godmother appeared, a vision of grace and kindness. With a wave of her wand, she transformed Cinderella's tattered rags into a breathtaking gown, her worn-out shoes into sparkling glass slippers, and a pumpkin into a magnificent carriage.

Overwhelmed with gratitude, Cinderella set off for the palace, her heart filled with hope and anticipation. But her fairy godmother warned her to return before midnight, as the magic would wear off, leaving her true identity exposed.

Arriving at the palace, Cinderella was greeted with awe and admiration, her beauty and grace captivating all who beheld her. She danced with the prince, lost in the magic of the moment, until the clock struck midnight, and reality came crashing down.

Remembering her godmother's warning, Cinderella fled the palace, leaving behind only a single glass slipper as a token of their fleeting encounter. As she raced through the streets, the carriage reverted to its humble form, and Cinderella found herself once again in rags.

But despite the setback, Cinderella clung to the memory of the magical night, cherishing the hope it had ignited within her. And as fate would have it, the prince was determined to find his mysterious maiden, using the glass slipper as his only clue.

Across the kingdom, the prince searched for the owner of the glass slipper, determined to find the woman who had captured his heart. When he arrived at Cinderella's home, her stepsisters eagerly tried to fit into the delicate shoe, but it was no use.

In a twist of fate, Cinderella's kindness and grace shone through, and she was finally reunited with her prince. As she slipped her foot into the glass slipper, it fit perfectly, confirming her identity as the one true love the prince had been searching for.

Overjoyed, the prince whisked Cinderella away to the palace, where they were married in a lavish ceremony attended by all the kingdom's nobles. And as they exchanged vows, Cinderella forgave her stepfamily for their cruelty, inviting them to live in the palace with her and the prince.

With kindness and love, Cinderella and her prince ruled the kingdom together, their fairy tale ending a testament to the enduring power of hope, courage, and true love. And as they lived happily ever after, Cinderella's story became a timeless tale of resilience and redemption, inspiring generations to come."""

from nltk.tokenize import RegexpTokenizer
tk = RegexpTokenizer("\w+")
tokens = tk.tokenize(story)
str(tokens)

from nltk.tokenize import word_tokenize
tokens2 = word_tokenize(story)
tokens2

len(tokens)

from nltk.stem import SnowballStemmer
lc=SnowballStemmer('english')

tokenized_sentence = []
for token in tokens:
    tokenized_sentence.append(lc.stem(token))
tokenized_sentence = " ".join(tokenized_sentence)
tokenized_sentence

nltk.download('stopwords')
from nltk.corpus import stopwords
stop_words = stopwords.words('english')
print(stop_words)

if type(stop_words)==list:
  stop_words.append(',')
  stop_words.append(':')
  stop_words.append(',')
  stop_words.remove('it')
  stop_words = set(stop_words)
sstop_words = [token for token in tokens if token.lower() not in stop_words]



print(sstop_words)

len(sstop_words)

from collections import Counter
word_counts = Counter(tokens)

most_frequent_words = word_counts.most_common(15)
print(most_frequent_words)

import spacy

nlp = spacy.load("en_core_web_sm")
doc = nlp(story)
main_character = []
for ent in doc.ents:
    if ent.label_ == "PERSON":
        main_character.append(ent.text)
        break

print(f"Main character: {main_character}")